sudo: false
branches:
  only:
    - master
language: ruby
cache: bundler
env:
  - RAILS_VERSION=4.0
  - RAILS_VERSION=3.2
rvm:
  - 1.9.3
  - 2.1.2

script: bundle exec rspec
before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:migrate
  - bundle exec rake app:db:test:prepare

